// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.actor.defs

import (
	appbskytypes "github.com/agentio/atiquette/api/app/bsky"
	comatprototypes "github.com/agentio/atiquette/api/com/atproto"
)

// ActorDefs_ProfileViewBasic is a "profileViewBasic" in the chat.bsky.actor.defs schema.
type ActorDefs_ProfileViewBasic struct {
	Associated *appbskytypes.ActorDefs_ProfileAssociated `json:"associated,omitempty" cborgen:"associated,omitempty"`
	Avatar     *string                                   `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// chatDisabled: Set to true when the actor cannot actively participate in conversations
	ChatDisabled *bool                                     `json:"chatDisabled,omitempty" cborgen:"chatDisabled,omitempty"`
	Did          string                                    `json:"did" cborgen:"did"`
	DisplayName  *string                                   `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle       string                                    `json:"handle" cborgen:"handle"`
	Labels       []*comatprototypes.LabelDefs_Label        `json:"labels,omitempty" cborgen:"labels,omitempty"`
	Verification *appbskytypes.ActorDefs_VerificationState `json:"verification,omitempty" cborgen:"verification,omitempty"`
	Viewer       *appbskytypes.ActorDefs_ViewerState       `json:"viewer,omitempty" cborgen:"viewer,omitempty"`
}
