// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package chat

// schema: chat.bsky.actor.declaration

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("chat.bsky.actor.declaration", &ActorDeclaration{})
}

// RECORDTYPE: ActorDeclaration
type ActorDeclaration struct {
	LexiconTypeID string `json:"$type,const=chat.bsky.actor.declaration" cborgen:"$type,const=chat.bsky.actor.declaration"`
	AllowIncoming string `json:"allowIncoming" cborgen:"allowIncoming"`
}
