// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package bsky

// schema: app.bsky.graph.follow

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("app.bsky.graph.follow", &GraphFollow{})
}

// RECORDTYPE: GraphFollow
type GraphFollow struct {
	LexiconTypeID string `json:"$type,const=app.bsky.graph.follow" cborgen:"$type,const=app.bsky.graph.follow"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Subject       string `json:"subject" cborgen:"subject"`
}
