// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.identity.requestPlcOperationSignature

import (
	"context"

	"github.com/agentio/atiquette/pkg/xrpc"
)

// IdentityRequestPlcOperationSignature calls the XRPC method "com.atproto.identity.requestPlcOperationSignature".
func IdentityRequestPlcOperationSignature(ctx context.Context, c xrpc.Client) error {
	if err := c.Do(ctx, xrpc.Procedure, "", "com.atproto.identity.requestPlcOperationSignature", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
