// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package atproto

// schema: com.atproto.server.deleteSession

import (
	"context"

	"github.com/agentio/atiquette/pkg/xrpc"
)

// ServerDeleteSession calls the XRPC method "com.atproto.server.deleteSession".
func ServerDeleteSession(ctx context.Context, c xrpc.Client) error {
	if err := c.Do(ctx, xrpc.Procedure, "", "com.atproto.server.deleteSession", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
