// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package noted

// schema: at.noted.link

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("at.noted.link", &Link{})
}

// RECORDTYPE: Link
type Link struct {
	LexiconTypeID string   `json:"$type,const=at.noted.link" cborgen:"$type,const=at.noted.link"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Description   *string  `json:"description,omitempty" cborgen:"description,omitempty"`
	Tags          []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	Title         *string  `json:"title,omitempty" cborgen:"title,omitempty"`
	Url           string   `json:"url" cborgen:"url"`
}
