// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package noted

// schema: at.noted.note

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("at.noted.note", &Note{})
}

// RECORDTYPE: Note
type Note struct {
	LexiconTypeID string `json:"$type,const=at.noted.note" cborgen:"$type,const=at.noted.note"`
	Body          string `json:"body" cborgen:"body"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Title         string `json:"title" cborgen:"title"`
}
