// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package noted

// schema: at.noted.post

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("at.noted.post", &Post{})
}

// RECORDTYPE: Post
type Post struct {
	LexiconTypeID string   `json:"$type,const=at.noted.post" cborgen:"$type,const=at.noted.post"`
	Body          *string  `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     *string  `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Extended      *string  `json:"extended,omitempty" cborgen:"extended,omitempty"`
	Slug          string   `json:"slug" cborgen:"slug"`
	Tags          []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	Title         string   `json:"title" cborgen:"title"`
}
